Edu r2d2
info-2-tp/machine pull request #3
Opened 2019-07-03 22:13 UTC by edu-matic

Con librerias de exp3

2019-07-03 22:58 UTC, LaMaldicionDeMandos requested changes

2019-07-03 22:58 UTC, LaMaldicionDeMandos commented on Prueba_1/src/main.c
> +volatile uint32_t Demora_LCD;
Fijate que pasa si borras todas esas variables volatiles que no usamos

2019-07-22 02:45 UTC, edu-matic commented on Prueba_1/src/main.c
> +volatile uint32_t Demora_LCD;
Marce ya probé y me tiro como 39 errores jaja. Ya subí la prueba 2 que esta hecha con las librerías que nos dieron en info2 y por suerte no tiene todas esas variable.

2019-08-07 22:50 UTC, LaMaldicionDeMandos approved these changes

2019-09-05 00:43 UTC, LaMaldicionDeMandos requested changes

2019-09-05 00:43 UTC, LaMaldicionDeMandos commented on Estados/CONTANDO/src/funciones.c
> +#include <PR_Teclado.h>
Estos defines tambien los vi en el main, meteles en funciones.h, asi los agregamos solo una vez.

2019-09-05 00:43 UTC, LaMaldicionDeMandos commented on Estados/CONTANDO/src/funciones.c
> +	}
Acá no podes hacer directamente `Relays(RELAY0, modo);` ?

2019-09-05 00:43 UTC, LaMaldicionDeMandos commented on Estados/CONTANDO/src/funciones.c
> +	Relays(RELAY3,OFF);//motor cuchilla
A alto nivel, seria mejor en vez de usar RELAYX, yo definiria algo asi:
`#define SENSOR RELAY0
#define MOTOR_BASE RELAY1
#define MOTOR_TORRE RELAY2
#define MOTOR_CUCHILLA RELAY3
`

2019-09-05 00:43 UTC, LaMaldicionDeMandos commented on Estados/CONTANDO/src/funciones.c
> +	Relays(RELAY2,ON);//motor torre
Esto podria quedar como 
`Relays(MOTOR_BASE, ON);
Relays(MOTOR_TORRE, ON);`

2019-09-05 00:43 UTC, LaMaldicionDeMandos commented on Estados/CONTANDO/src/funciones.c
> +	if((pulsadorFinVuelta()==1) && (pulsadorFinTecho()==1) )
quedaria mas lindo así: `if (puldadorFinVuelta() && pulsadorFinTecho())`

2019-09-05 00:43 UTC, LaMaldicionDeMandos commented on Estados/CONTANDO/src/funciones.c
> +	if((pulsadorFinTecho()==0) && (pulsadorFinVuelta()==0) )
igual que el otro: `if (!puldadorFinVuelta() && !pulsadorFinTecho())`

2019-09-05 00:43 UTC, LaMaldicionDeMandos commented on Estados/CONTANDO/src/funciones.c
> +	if((pulsadorFinVuelta()==0) )
acá no seria un `else`?

2019-09-05 00:43 UTC, LaMaldicionDeMandos commented on Estados/CONTANDO/src/funciones.h
> +#define LINE_1 1
`#define FIRST_LINE #define SECOND_LINE`

2019-09-11 22:45 UTC, LaMaldicionDeMandos approved these changes

2019-09-11 22:45 UTC, LaMaldicionDeMandos commented on Estados/CONTANDO/src/funciones.c
> +		orden=TRUE;
se puede hacer directamente return GetKey() == PULSADOR_INICIAR;

2019-09-11 22:45 UTC, LaMaldicionDeMandos commented on Estados/CONTANDO/src/funciones.c
> +	if(boton_ok()== TRUE){
podes sacar el == TRUE

2019-09-11 22:50 UTC, LaMaldicionDeMandos commented
nada

2019-09-11 22:52 UTC, merged